/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as CatalogAnimeIdIndexRouteImport } from './routes/catalog/$animeId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogAnimeIdIndexRoute = CatalogAnimeIdIndexRouteImport.update({
  id: '/catalog/$animeId/',
  path: '/catalog/$animeId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/catalog/$animeId': typeof CatalogAnimeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/catalog/$animeId': typeof CatalogAnimeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/catalog/$animeId/': typeof CatalogAnimeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalog' | '/catalog/$animeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalog' | '/catalog/$animeId'
  id: '__root__' | '/' | '/catalog/' | '/catalog/$animeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  CatalogAnimeIdIndexRoute: typeof CatalogAnimeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$animeId/': {
      id: '/catalog/$animeId/'
      path: '/catalog/$animeId'
      fullPath: '/catalog/$animeId'
      preLoaderRoute: typeof CatalogAnimeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  CatalogAnimeIdIndexRoute: CatalogAnimeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
